# PRIS data Analysis
In this notebook I will analyze the content downloaded from the IAEA 2023 report on Nuclear Power Reactors in the world.

## Step 0: Combining data in one database
The interesting data is from tables 9 to 14, they contain:
- TABLE 9. CONSTRUCTION STARTS DURING 2023
- TABLE 10. CONNECTIONS TO THE GRID DURING 2023
- TABLE 11. SCHEDULED CONNECTIONS TO THE GRID DURING 2023
- TABLE 12. REACTORS PLANNED FOR CONSTRUCTION AS KNOWN ON 31 DEC. 2023
- TABLE 13. REACTORS UNDER CONSTRUCTION, 31 DEC. 2023
- TABLE 14. OPERATIONAL REACTORS, 31 DEC. 2023
So we are going to combine the lists and add a new label for their status

In [1]:
#%pip install pandas
import pandas as pd

In [2]:
pris_DB_columns = [
    "Country", "Code", "Reactor Name", "Type", "Model", "Thermal Capacity (MWth)", "Gross Capacity (MWe)", "Net Capacity (MWe)",
    "Operator", "nsss Supplier", "Construction Starts", "Grid Connection", "Availability", "Capacity Factor","Status"
]

Construction starts this Year 2023

In [3]:
# Read Excel file /data/IAEA - PRIS data/2023-Table9.xlsx
file_path = '../Data/IAEA - PRIS data/2023-Table9.xlsx'
# Ignore rows
skip_rows = [0, 1, 2, 11, 12]
df = pd.read_excel(file_path, skiprows=skip_rows, header=None)

# Ignore columns
skip_columns = [0,12,13]
df = df.drop(columns=skip_columns)

# Skip the rows used for the original column names and reset index
df = df.iloc[2:].reset_index(drop=True)

# Add new column
df["Grid Connection"] = "TBD"
df["Availability"] = "TBD"
df["Capacity Factor"] = "TBD"
df["Status"] = "Construction starts 2023"

# Rename Columns
df.columns = pris_DB_columns
# Populate empty columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Rename
df_StartsConstruction = df.copy()

FileNotFoundError: [Errno 2] No such file or directory: '../Data/IAEA - PRIS data/2023-Table9.xlsx'

Connected in 2023

In [ ]:
# Read Excel file /data/IAEA - PRIS data/2023-Table9.xlsx
file_path = '../Data/IAEA - PRIS data/2023-Table10.xlsx'
# Ignore rows
skip_rows = [0, 1, 2, 3, 11, 12]
df = pd.read_excel(file_path, skiprows=skip_rows, header=None)

# Ignore columns
skip_columns = [0,12]
df = df.drop(columns=skip_columns)

# Skip the rows used for the original column names and reset index
df = df.iloc[2:].reset_index(drop=True)

# Add new column
df["Availability"] = "TBD"
df["Capacity Factor"] = "TBD"
df["Status"] = "Connected in 2023"
# Rename Columns
df.columns = pris_DB_columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Rename
df_JustConnected = df.copy()

FileNotFoundError: [Errno 2] No such file or directory: '../Data/IAEA - PRIS data/2023-Table10.xlsx'

Scheduled Connection in the next year (2024)

In [ ]:
# Read Excel file
file_path = '../Data/IAEA - PRIS data/2023-Table11.xlsx'
# Ignore rows
skip_rows = [0, 1, 2, 3, 11, 12]
df = pd.read_excel(file_path, skiprows=skip_rows, header=None)

# Ignore columns
skip_columns = [0,12]
df = df.drop(columns=skip_columns)

# Skip the rows used for the original column names and reset index
df = df.iloc[2:].reset_index(drop=True)

# Add new column
df["Availability"] = "TBD"
df["Capacity Factor"] = "TBD"
df["Status"] = "Connection Scheduled Soon"
# Rename Columns
df.columns = pris_DB_columns


# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Rename
df_ScheduledConnection = df.copy()

FileNotFoundError: [Errno 2] No such file or directory: '../Data/IAEA - PRIS data/2023-Table11.xlsx'

Planned Construction

In [ ]:
# Read Excel file
file_path = '../Data/IAEA - PRIS data/2023-Table12.xlsx'
# Ignore rows
skip_rows = [0, 1, 2, 3, 11, 53, 54]
df = pd.read_excel(file_path, skiprows=skip_rows, header=None)

# Ignore columns
skip_columns = [0]
df = df.drop(columns=skip_columns)

# Skip the rows used for the original column names and reset index
df = df.iloc[2:].reset_index(drop=True)

# Add new column
df["Grid Connection"] = "TBD"
df["Availability"] = "TBD"
df["Capacity Factor"] = "TBD"
df["Status"] = "Construction Planned"
# Rename Columns
df.columns = pris_DB_columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Where Construction Starts is empty put TBD
df["Construction Starts"] = df["Construction Starts"].replace(["", None, pd.NA], "TBD")

# Rename
df_PlannedConstruction = df.copy()

In [ ]:
# Read Excel file
file_path = '../Data/IAEA - PRIS data/2023-Table13.xlsx'
# Ignore rows
skip_rows = [0, 1, 2, 3, 65, 66]
df = pd.read_excel(file_path, skiprows=skip_rows, header=None)

# Ignore columns
skip_columns = [0,2,13,15]
df = df.drop(columns=skip_columns)

# Skip the rows used for the original column names and reset index
df = df.iloc[2:].reset_index(drop=True)

# Add new column
df["Grid Connection"] = "TBD"
df["Availability"] = "TBD"
df["Status"] = "Under Construction"

# Rename Columns
df.columns = pris_DB_columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Replace empty values with TBD
df["Grid Connection"] = df["Grid Connection"].replace(["", None, pd.NA], "TBD")

# Rename Columns
df.columns = pris_DB_columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Rename
df_UnderConstruction = df.copy()

Operational Reactors as of 2023

In [ ]:
# Read Excel file
file_path = '../Data/IAEA - PRIS data/2023-Table14.xlsx'
# Ignore rows
skip_rows = [417, 418, 419, 420, 421, 422, 423]
df = pd.read_excel(file_path, skiprows=skip_rows, header=None)
# Ignore columns
skip_columns = [0,13,16,17,18]
df = df.drop(columns=skip_columns)

# Skip the rows used for the original column names and reset index
df = df.iloc[6:].reset_index(drop=True)

# Add new column
df["Status"] = "Under Construction"

# Rename Columns
df.columns = pris_DB_columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()


# Rename Columns
df.columns = pris_DB_columns

# Forward fill only on the first column since they used merged cells
df["Country"] = df["Country"].ffill()

# Rename
df_Operational = df.copy()

The interesting data is from tables 9 to 14, they contain:
- TABLE 9. CONSTRUCTION STARTS DURING 2023
- TABLE 10. CONNECTIONS TO THE GRID DURING 2023
- TABLE 11. SCHEDULED CONNECTIONS TO THE GRID DURING 2024
- TABLE 12. REACTORS PLANNED FOR CONSTRUCTION AS KNOWN ON 31 DEC. 2023
- TABLE 13. REACTORS UNDER CONSTRUCTION, 31 DEC. 2023
- TABLE 14. OPERATIONAL REACTORS, 31 DEC. 2023

We can group some of this:
Connection during 2023 and scheduled connections during 2024 can all be grouped in "ScheduledConnection" status
Construction starts 2023 and under construction all "UnderConstrcion"
Then we have operationl and planned

In [ ]:
df_StartsConstruction["Status"] = "Under Construction"
df_UnderConstruction["Status"] = "Under Construction"

df_PlannedConstruction["Status"] = "Planned Construction"

df_JustConnected["Status"] = "Scheduled Connected"
df_ScheduledConnection["Status"] = "Scheduled Connection"

df_Operational["Status"] = "Operational"

# Unite all DataFrames
df_Complete = pd.concat([df_StartsConstruction, df_UnderConstruction, df_PlannedConstruction, df_JustConnected, df_ScheduledConnection, df_Operational], ignore_index=True)

# Display the final DataFrame
pd.options.display.max_columns = None  # Show all columns
display(df_Complete)

(532, 15)

In [ ]:
# List all Countries
countries = df_Complete["Country"].unique()
display(countries)

array(['CHINA', 'EGYPT', 'ARGENTINA', 'BANGLADESH', 'BRAZIL', 'FRANCE',
       'INDIA', 'IRAN,ISL.REP', 'JAPAN', 'KOREA,REP.OF', 'RUSSIA',
       'SLOVAKIA', 'TÜRKIYE', 'UAE', 'UK', 'UKRAINE', 'USA', 'FINLAND',
       'HUNGARY', 'BELARUS', 'ARMENIA', 'BELGIUM', 'BULGARIA', 'CANADA',
       'CZECH REP.', 'MEXICO', 'NETHERLANDS', 'PAKISTAN', 'ROMANIA',
       'SLOVENIA', 'SOUTH AFRICA', 'SPAIN', 'SWEDEN', 'SWITZERLAND'],
      dtype=object)

In [ ]:
# Exclude countries known to only work within its orders
To_exclude = ['CHINA', 'RUSSIA', 'IRAN', 'INDIA', 'BELARUS', 'PAKISTAN']
# Exclude this from the df
df_Countries_Filtered = df_Complete[~df_Complete["Country"].isin(To_exclude)]

In [ ]:
# List all nsss Suppliers
nsss_suppliers = df_Countries_Filtered["nsss Supplier"].unique()
display(nsss_suppliers)

array(['JSC ASE', 'CNEA', 'AEM', 'KWU', 'FRAM', 'H/G', 'HITACHI',
       'DHICKOPC', 'ŠKODA ', 'KEPCO', 'ORANO', 'WH', nan, 'MHI',
       'SIEMENS', 'AECL', 'FAEA', 'ACECOWEN', 'ACLF', 'AEE', 'OH/AECL',
       'ASEASTAL', 'WH/MHI', 'DHICKAEC', 'AECL/DHI', 'GE', 'S/KWU',
       'ABB ATOM', 'GETSCO', 'NPC', 'NNC', 'PPC', 'PAIP', 'PAA', 'B&W',
       'CE'], dtype=object)

In [ ]:
operator_country_array = [
    ["JSC ASE", "Russia"],
    ["CNEA", "Argentina"],
    ["AEM", "Russia"],
    ["KWU", "Germany"],
    ["FRAM", "France"],
    ["H/G", "Japan"],
    ["HITACHI", "Japan"],
    ["DHICKOPC", "Korea"],
    ["ŠKODA", "Czech"],
    ["KEPCO", "Korea"],
    ["ORANO", "France"],
    ["WH", "US"],
    ["nan", "Japan (GE Hitachi Nuclear Energy or Toshiba)"],
    ["MHI", "US/Japan"],
    ["SIEMENS", "Germany"],
    ["AECL", "Canada"],
    ["FAEA", "US"],
    ["ACECOWEN", "US/Belgium"],
    ["ACLF", "France/Belgium"],
    ["AEE", "Russia"],
    ["OH/AECL", "Canada"],
    ["ASEASTAL", "Finland"],
    ["WH/MHI", "Japan/US"],
    ["DHICKAEC", "Korea"],
    ["AECL/DHI", "Canada"],
    ["GE", "US"],
    ["S/KWU", "Germany"],
    ["ABB ATOM", "Sweden"],
    ["GETSCO", "US"],
    ["NPC", "UK"],
    ["NNC", "UK"],
    ["PPC", "UK"],
    ["PAIP", "Russia"],
    ["PAA", "Russia"],
    ["B&W", "US"],
    ["CE", "US"]
]
# get those that contain in the second element one of the countries from To_Exclude
filtered_operators = [op for op in operator_country_array if op[1].upper() not in To_exclude]
# filtered_operators = [[op[0].upper(), op[1].upper()] for op in filtered_operators]
print("Operators that are not in the excluded countries:")
for op in filtered_operators:
    print(f" - {op[0]} ({op[1]})")

Operators that are not in the excluded countries:
 - CNEA (Argentina)
 - KWU (Germany)
 - FRAM (France)
 - H/G (Japan)
 - HITACHI (Japan)
 - DHICKOPC (Korea)
 - ŠKODA (Czech)
 - KEPCO (Korea)
 - ORANO (France)
 - WH (US)
 - nan (Japan (GE Hitachi Nuclear Energy or Toshiba))
 - MHI (US/Japan)
 - SIEMENS (Germany)
 - AECL (Canada)
 - FAEA (US)
 - ACECOWEN (US/Belgium)
 - ACLF (France/Belgium)
 - OH/AECL (Canada)
 - ASEASTAL (Finland)
 - WH/MHI (Japan/US)
 - DHICKAEC (Korea)
 - AECL/DHI (Canada)
 - GE (US)
 - S/KWU (Germany)
 - ABB ATOM (Sweden)
 - GETSCO (US)
 - NPC (UK)
 - NNC (UK)
 - PPC (UK)
 - B&W (US)
 - CE (US)

In [ ]:
# Filter out operators from excluded countries from the df
df_Countries_Filtered_2 = df_Countries_Filtered[df_Countries_Filtered["nsss Supplier"].isin([op[0] for op in filtered_operators])]
display(df_Countries_Filtered_2)

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
6,ARGENTINA,AR -4,CAREM25,PWR,CAREM Prototyp,100,29,25,CNEA,CNEA,2015-8,TBD,TBD,TBD,Under Construction
9,BRAZIL,BR -3,ANGRA-3,PWR,PRE KONVOI,3900,1405,1340,ELETRONU,KWU,2010-5,2028-3,TBD,TBD,Under Construction
37,FRANCE,FR -74,FLAMANVILLE-3,PWR,EPR,4300,1650,1630,EDF,FRAM,2007-12,TBD,TBD,TBD,Under Construction
47,JAPAN,JP -66,OHMA,BWR,ABWR,3926,1383,1328,EPDC,H/G,2010-5,TBD,TBD,TBD,Under Construction
48,JAPAN,JP -65,SHIMANE-3,BWR,ABWR,3926,1373,1325,CHUGOKU,HITACHI,2006-10,TBD,TBD,TBD,Under Construction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,USA,US -499,SOUTH TEXAS-2,PWR,WH 4LP (DRYAMB,3853,1354,1280,STP,WH,1975-12,1989-4,85.1,85.1,Operational
528,USA,US -5025,VOGTLE-3,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-3,2023-3,100,100,Operational
529,USA,US -528,PALO VERDE-1,PWR,CE80 2LP (DRYA,3990,1414,1311,APS,CE,1976-5,1985-6,83.1,83.2,Operational
530,USA,US -529,PALO VERDE-2,PWR,CE80 2LP (DRYA,3990,1414,1314,APS,CE,1976-6,1986-5,85,85,Operational
531,USA,US -530,PALO VERDE-3,PWR,CE80 2LP (DRYA,3990,1414,1312,APS,CE,1976-6,1987-11,86.8,87,Operational

In [ ]:
# Only consider those with a grid connection that is either TBD or after 1986 (yyyy-mm format)
def age_limit(val):
    if val == "TBD":
        return True
    try:
        year = int(str(val).split('-')[0])
        return year > 2000
    except Exception:
        return False
# Either apply it to the grid connection or the construction starting date, the result is basically the same
df_Age_Filtered = df_Countries_Filtered_2[df_Countries_Filtered_2["Construction Starts"].apply(age_limit)]
display(df_Age_Filtered)

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
6,ARGENTINA,AR -4,CAREM25,PWR,CAREM Prototyp,100,29,25,CNEA,CNEA,2015-8,TBD,TBD,TBD,Under Construction
9,BRAZIL,BR -3,ANGRA-3,PWR,PRE KONVOI,3900,1405,1340,ELETRONU,KWU,2010-5,2028-3,TBD,TBD,Under Construction
37,FRANCE,FR -74,FLAMANVILLE-3,PWR,EPR,4300,1650,1630,EDF,FRAM,2007-12,TBD,TBD,TBD,Under Construction
47,JAPAN,JP -66,OHMA,BWR,ABWR,3926,1383,1328,EPDC,H/G,2010-5,TBD,TBD,TBD,Under Construction
48,JAPAN,JP -65,SHIMANE-3,BWR,ABWR,3926,1373,1325,CHUGOKU,HITACHI,2006-10,TBD,TBD,TBD,Under Construction
49,"KOREA,REP.OF",KR -29,SAEUL-3,PWR,APR-1400,3983,1400,1340,KHNP,DHICKOPC,2017-4,TBD,TBD,TBD,Under Construction
50,"KOREA,REP.OF",KR -30,SAEUL-4,PWR,APR-1400,3983,1400,1340,KHNP,DHICKOPC,2018-9,TBD,TBD,TBD,Under Construction
59,UAE,AE -04,BARAKAH-4,PWR,APR-1400,3983,1417,1310,NAWAH,KEPCO,2015-7,2024-3,TBD,TBD,Under Construction
60,UK,GB -25A,HINKLEY POINT C-1,PWR,EPR-1750,4524,1720,1630,EDF-CGN,ORANO,2018-12,TBD,TBD,TBD,Under Construction
61,UK,GB -25B,HINKLEY POINT C-2,PWR,EPR-1750,4524,1720,1630,EDF-CGN,ORANO,2019-12,TBD,TBD,TBD,Under Construction
64,USA,US -5026,VOGTLE-4,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-11,2024-3,TBD,TBD,Under Construction
85,JAPAN,JP -69,HIGASHI DORI-1 (TEPCO),BWR,ABWR,3926,1385,1343,TEPCO,H/G,TBD,TBD,TBD,TBD,Planned Construction
91,JAPAN,JP -67,TSURUGA-3,PWR,APWR,4466,1538,1475,JAPCO,MHI,TBD,TBD,TBD,TBD,Planned Construction
92,JAPAN,JP -68,TSURUGA-4,PWR,APWR,4466,1538,1475,JAPCO,MHI,TBD,TBD,TBD,TBD,Planned Construction
113,"KOREA,REP.OF",KR -28,SHIN-HANUL-2,PWR,APR-1400,3983,1455,1340,KHNP,DHICKOPC,2013-6,2023-12,TBD,TBD,Scheduled Connected
115,USA,US -5025,VOGTLE-3,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-3,2023-3,TBD,TBD,Scheduled Connected
119,UAE,AE -04,BARAKAH-4,PWR,APR-1400,3983,1417,1310,NAWAH,KEPCO,2015-7,2024-3,TBD,TBD,Scheduled Connection
120,USA,US -5026,VOGTLE-4,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-11,2024-3,TBD,TBD,Scheduled Connection
220,FINLAND,FI -5,OLKILUOTO-3,PWR,EPR,4300,1660,1600,TVO,FRAM,2005-8,2022-3,96.3,96.9,Operational
325,"KOREA,REP.OF",KR -21,SHIN-KORI-1,PWR,OPR-1000,2825,1048,996,KHNP,DHICKOPC,2006-6,2010-8,77,78,Operational
326,"KOREA,REP.OF",KR -22,SHIN-KORI-2,PWR,OPR-1000,2825,1047,996,KHNP,DHICKOPC,2007-6,2012-1,83.9,84.9,Operational
327,"KOREA,REP.OF",KR -23,SHIN-WOLSONG-1,PWR,OPR-1000,2825,1048,997,KHNP,DHICKOPC,2007-11,2012-1,82.8,83.1,Operational
328,"KOREA,REP.OF",KR -24,SHIN-WOLSONG-2,PWR,OPR-1000,2825,1048,993,KHNP,DHICKOPC,2008-9,2015-2,85.3,85.5,Operational
329,"KOREA,REP.OF",KR -25,SAEUL-1,PWR,APR-1400,3983,1488,1416,KHNP,DHICKOPC,2008-10,2016-1,79.2,79.3,Operational
330,"KOREA,REP.OF",KR -26,SAEUL-2,PWR,APR-1400,3983,1491,1418,KHNP,DHICKOPC,2009-8,2019-4,84.1,84.3,Operational
331,"KOREA,REP.OF",KR -27,SHIN-HANUL-1,PWR,APR-1400,3983,1455,1414,KHNP,DHICKOPC,2012-7,2022-6,99.3,99.7,Operational
332,"KOREA,REP.OF",KR -28,SHIN-HANUL-2,PWR,APR-1400,3983,1455,1340,KHNP,DHICKOPC,2013-6,2023-12,0,0,Operational
412,UAE,AE -01,BARAKAH-1,PWR,APR-1400,3983,1417,1337,NAWAH,KEPCO,2012-7,2020-8,81.1,81.7,Operational
413,UAE,AE -02,BARAKAH-2,PWR,APR-1400,3983,1417,1337,NAWAH,KEPCO,2013-4,2021-9,92,92.5,Operational
414,UAE,AE -03,BARAKAH-3,PWR,APR-1400,3983,1417,1337,NAWAH,KEPCO,2014-9,2022-10,96.8,97.4,Operational
528,USA,US -5025,VOGTLE-3,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-3,2023-3,100,100,Operational

In [ ]:
models = df_Age_Filtered["Model"].unique()
print(len(models), "unique models found:")
for m in models:
    print(f"- {m}")

9 unique models found:
- CAREM Prototyp
- PRE KONVOI
- EPR
- ABWR
- APR-1400
- EPR-1750
- AP-1000
- APWR
- OPR-1000

In [ ]:
models_to_study = ["EPR", "APR-1400", "EPR-1750", "AP-1000", "APWR"]
df_filtered_models = df_Countries_Filtered[df_Countries_Filtered["Model"].isin(models_to_study)]

In [ ]:
# Let's see each model in more detail
for m in models_to_study:
    display(m)
    display(df_filtered_models[df_filtered_models["Model"] == m])

'EPR'

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
37,FRANCE,FR -74,FLAMANVILLE-3,PWR,EPR,4300,1650,1630,EDF,FRAM,2007-12,TBD,TBD,TBD,Under Construction
220,FINLAND,FI -5,OLKILUOTO-3,PWR,EPR,4300,1660,1600,TVO,FRAM,2005-8,2022-3,96.3,96.9,Operational

'APR-1400'

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
49,"KOREA,REP.OF",KR -29,SAEUL-3,PWR,APR-1400,3983,1400,1340,KHNP,DHICKOPC,2017-4,TBD,TBD,TBD,Under Construction
50,"KOREA,REP.OF",KR -30,SAEUL-4,PWR,APR-1400,3983,1400,1340,KHNP,DHICKOPC,2018-9,TBD,TBD,TBD,Under Construction
59,UAE,AE -04,BARAKAH-4,PWR,APR-1400,3983,1417,1310,NAWAH,KEPCO,2015-7,2024-3,TBD,TBD,Under Construction
113,"KOREA,REP.OF",KR -28,SHIN-HANUL-2,PWR,APR-1400,3983,1455,1340,KHNP,DHICKOPC,2013-6,2023-12,TBD,TBD,Scheduled Connected
119,UAE,AE -04,BARAKAH-4,PWR,APR-1400,3983,1417,1310,NAWAH,KEPCO,2015-7,2024-3,TBD,TBD,Scheduled Connection
329,"KOREA,REP.OF",KR -25,SAEUL-1,PWR,APR-1400,3983,1488,1416,KHNP,DHICKOPC,2008-10,2016-1,79.2,79.3,Operational
330,"KOREA,REP.OF",KR -26,SAEUL-2,PWR,APR-1400,3983,1491,1418,KHNP,DHICKOPC,2009-8,2019-4,84.1,84.3,Operational
331,"KOREA,REP.OF",KR -27,SHIN-HANUL-1,PWR,APR-1400,3983,1455,1414,KHNP,DHICKOPC,2012-7,2022-6,99.3,99.7,Operational
332,"KOREA,REP.OF",KR -28,SHIN-HANUL-2,PWR,APR-1400,3983,1455,1340,KHNP,DHICKOPC,2013-6,2023-12,0,0,Operational
412,UAE,AE -01,BARAKAH-1,PWR,APR-1400,3983,1417,1337,NAWAH,KEPCO,2012-7,2020-8,81.1,81.7,Operational
413,UAE,AE -02,BARAKAH-2,PWR,APR-1400,3983,1417,1337,NAWAH,KEPCO,2013-4,2021-9,92,92.5,Operational
414,UAE,AE -03,BARAKAH-3,PWR,APR-1400,3983,1417,1337,NAWAH,KEPCO,2014-9,2022-10,96.8,97.4,Operational

'EPR-1750'

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
60,UK,GB -25A,HINKLEY POINT C-1,PWR,EPR-1750,4524,1720,1630,EDF-CGN,ORANO,2018-12,TBD,TBD,TBD,Under Construction
61,UK,GB -25B,HINKLEY POINT C-2,PWR,EPR-1750,4524,1720,1630,EDF-CGN,ORANO,2019-12,TBD,TBD,TBD,Under Construction

'AP-1000'

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
64,USA,US -5026,VOGTLE-4,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-11,2024-3,TBD,TBD,Under Construction
115,USA,US -5025,VOGTLE-3,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-3,2023-3,TBD,TBD,Scheduled Connected
120,USA,US -5026,VOGTLE-4,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-11,2024-3,TBD,TBD,Scheduled Connection
528,USA,US -5025,VOGTLE-3,PWR,AP-1000,3400,1250,1117,SOUTHERN,WH,2013-3,2023-3,100,100,Operational

'APWR'

,Country,Code,Reactor Name,Type,Model,Thermal Capacity (MWth),Gross Capacity (MWe),Net Capacity (MWe),Operator,nsss Supplier,Construction Starts,Grid Connection,Availability,Capacity Factor,Status
90,JAPAN,JP -75,SENDAI-3,PWR,APWR,4466,1590,1590,KYUSHU,NaN,TBD,TBD,TBD,TBD,Planned Construction
91,JAPAN,JP -67,TSURUGA-3,PWR,APWR,4466,1538,1475,JAPCO,MHI,TBD,TBD,TBD,TBD,Planned Construction
92,JAPAN,JP -68,TSURUGA-4,PWR,APWR,4466,1538,1475,JAPCO,MHI,TBD,TBD,TBD,TBD,Planned Construction

### Model review
I will now look at each model to understand if:
- They are still available to be constructed as new
- The country that builds it does export it or if its only for internal use